server:
    port: 55425







roadnetwork:
    crosses:
        -   name: cfxj
            agentid: 1631933545182
            yellow: 3
            red: 2
            loss: 3
            phases:
                -   id: 1
                    flowperhour: 200
                    saturation: 1650
                -   id: 2
                    flowperhour: 200
                    saturation: 1650
                -   id: 3
                    flowperhour: 200
                    saturation: 1650
                -   id: 4
                    flowperhour: 200
                    saturation: 1650
                -   id: 5
                    flowperhour: 200
                    saturation: 1650
                -   id: 6
                    flowperhour: 200
                    saturation: 1650
                -   id: 7
                    flowperhour: 200
                    saturation: 1650
                -   id: 8
                    flowperhour: 200
                    saturation: 1650
            barriers:
                -   num: 1
                    items:
                        - ring: 1
                          data: [1, 2]
                        - ring: 2
                          data: [3, 4]
                -   num: 2
                    items:
                        - ring: 1
                          data: [5, 6]
                        - ring: 2
                          data: [7, 8]
            rings:
                -   num: 1
                    sequence: [1, 2, 5, 6]
                -   num: 2
                    sequence: [3, 4, 7, 8]
